package com.project.dto;

import lombok.Data;
@Data
public class CustomerDTO {
    private Long id;
    private String name;
    private String email;
    private String phoneNumber;
    private String address;

    // Constructors, getters, and setters can be generated by Lombok
}
